# Generated by Django 6.0.6 on 2026-07-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
