# Generated by Django 6.0.6 on 2026-07-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_trip_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
